### ISSUE TITLE
Hackage-ify?

### ISSUE THREAD

**Issue by isovector** [hacoo/haskell-jps#1]
Hiya! This looks like a great library, and I'm hoping to use it in a project of mine. Wondering if you have any plans to put it on hackage, and if not, whether you'd be OK with me doing so. Cheers!

**Comment by hacoo** [comment]
Hi! I have no hackage plans currently, but if you'd like to add it, go for it. That said: I hacked this together in a few weeks for a class project, and am NOT an experienced haskell programmer. While the performance is better than a naive A* implementation, there's probably all kinds of speed left on the table. 

Hope you find the code useful :)

**Comment by isovector** [comment]
Cool, thanks! I'll let you know if I move forward with it!
